import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import project.ConnectionProvider;
import project.SmsSender;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author divya
 */
public class EmpComplaint extends javax.swing.JFrame {
    String user="E001";
    private File f;
    public EmpComplaint() {
        initComponents();
    }
    public EmpComplaint(String user) {
        this.user=user;
        initComponents();
        jButton2.addActionListener(evt -> jButton2ActionPerformed(evt));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Complaint Type");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 170, 170, 21);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date of Incident");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 390, 170, 21);

        jComboBox1.setBackground(new java.awt.Color(255,255,255,80));
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Workload and Work Pressure", "Unfair Treatment or Discrimination", "Workplace Safety Issues", "Management Issues", "System or Software Issues", "Compensation and Benefits", "Inadequate Tools or Resources", "Others" }));
        jComboBox1.setBorder(null);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(790, 160, 350, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Description");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 280, 170, 21);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Urgency level");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 470, 170, 21);

        jSpinner2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jSpinner2.setModel(new javax.swing.SpinnerListModel(new String[] {"Low", "Medium", "High"}));
        jSpinner2.setBorder(null);
        getContentPane().add(jSpinner2);
        jSpinner2.setBounds(790, 460, 350, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Attachments");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(460, 550, 170, 21);

        jButton1.setBackground(new java.awt.Color(255,255,255,80));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Upload");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(790, 540, 350, 30);

        jButton2.setBackground(new java.awt.Color(255,255,255,80));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Submit");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 660, 100, 30);
        getContentPane().add(canvas1);
        canvas1.setBounds(0, 0, 0, 0);

        jDateChooser1.setBackground(new java.awt.Color(255,255,255,80));
        jDateChooser1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(790, 380, 350, 30);

        jPanel1.setBackground(new java.awt.Color(0,0,0,90));
        jPanel1.setLayout(null);

        jTextArea1.setBackground(new java.awt.Color(255,255,255,80));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(790, 240, 350, 87);

        jButton3.setBackground(new java.awt.Color(255,255,255,80));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("Close");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1050, 650, 90, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jLabel7.setPreferredSize(new java.awt.Dimension(134, 172));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(1170, 510, 140, 100);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Complaint Form");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(630, 50, 221, 29);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1540, 810);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\sem IV\\project\\login bg.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, -10, 1550, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         jButton2.setEnabled(false);
          if (f == null) {
            JOptionPane.showMessageDialog(this, "Please select an image file first.");
            jButton2.setEnabled(true);
            return;
           }

        String path=f.getAbsolutePath();
        boolean isSuccess=false;
        String message="You have recieved an complaint from the employee.";
    try
    {
        BufferedImage bi = ImageIO.read(f);
        Image img = bi.getScaledInstance(134, 172, Image.SCALE_SMOOTH);
        jLabel7.setIcon(new ImageIcon(img));
    }
    catch(IOException ex)   
    {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading image preview.");
    }
        String complaintType = (String) jComboBox1.getSelectedItem();
        String description = jTextArea1.getText();
        java.util.Date incidentDate;
        incidentDate = (java.util.Date) jDateChooser1.getDate();
         if (incidentDate == null) {
            JOptionPane.showMessageDialog(this, "Please select the incident date.");
            jButton2.setEnabled(true);
            return;
        }
        java.util.Date comDate = new java.util.Date(); 
        String urgencyLevel = (String) jSpinner2.getValue();

        String sql = "INSERT INTO Icomplaint (EmpID, Type, Description, Incident, ComDate, Level,image) VALUES (?, ?, ?, ?, ?, ?,?)";

        try (Connection con = ConnectionProvider.getCon(); 
            PreparedStatement pstmt = con.prepareStatement(sql);
            FileInputStream fis = new FileInputStream(f)){

            pstmt.setString(1, this.user); 
            pstmt.setString(2, complaintType);
            pstmt.setString(3, description);
            pstmt.setDate(4, new java.sql.Date(incidentDate.getTime()));
            pstmt.setDate(5, new java.sql.Date(comDate.getTime()));
            pstmt.setString(6, urgencyLevel);
            pstmt.setBinaryStream(7,fis,(int)f.length());

            pstmt.executeUpdate();
            fis.close();
            JOptionPane.showMessageDialog(this, "Complaint submitted successfully!");
            isSuccess=true;

        } catch (SQLException e) {
           JOptionPane.showMessageDialog(this, "Error submitting complaint: " + e.getMessage());
        } catch (IOException ex) {
            Logger.getLogger(EmpComplaint.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            jButton2.setEnabled(true);
    }
        if(isSuccess)
        {
          try
        {
            Connection con = ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select phone from adminlogin");
            while(rs.next())
            {
                String ph="+91"+rs.getString(1);
                SmsSender.sms(ph,message);
            }
        }
          catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Error: " + e.getMessage());
            setVisible(false);
        }
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         JFileChooser choose=new JFileChooser();
        int n= choose.showOpenDialog(null);
        if(n==JFileChooser.APPROVE_OPTION)
        {
            f=choose.getSelectedFile();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpComplaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpComplaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpComplaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpComplaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               EmpComplaint ecm = new EmpComplaint();
               ecm.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
               ecm.setVisible(true);
               ecm.toFront();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
