
import java.awt.BorderLayout;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import project.ConnectionProvider;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author divya
 */
public class EmployeeResolve extends javax.swing.JFrame {
    String user="E001";
    public EmployeeResolve() {
        initComponents();
         imageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (imageLabel.getIcon() != null) {
            Icon icon = imageLabel.getIcon();
            ImageIcon imgIcon = (ImageIcon) icon;
            Image img = imgIcon.getImage();
            JFrame imageFrame = new JFrame("Image Viewer");
            imageFrame.setSize(600, 600);
            imageFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            imageFrame.setLayout(new BorderLayout());
            Image scaledImg = getScaledImage(img, imageFrame.getWidth(), imageFrame.getHeight());
            ImageIcon scaledIcon = new ImageIcon(scaledImg);
            JLabel fullImageLabel = new JLabel(scaledIcon);
            fullImageLabel.setHorizontalAlignment(JLabel.CENTER);
            fullImageLabel.setVerticalAlignment(JLabel.CENTER);
            imageFrame.add(fullImageLabel, BorderLayout.CENTER);
            imageFrame.setVisible(true);
        }
    }
});
    }
   public static Image getScaledImage(Image srcImg, int targetWidth, int targetHeight) {
    int imgWidth = srcImg.getWidth(null);
    int imgHeight = srcImg.getHeight(null);
    double scaleX = (double) targetWidth / imgWidth;
    double scaleY = (double) targetHeight / imgHeight;
    double scaleFactor = Math.min(scaleX, scaleY);
    int newWidth = (int) (imgWidth * scaleFactor);
    int newHeight = (int) (imgHeight * scaleFactor);
    BufferedImage bufferedImg = new BufferedImage(newWidth, newHeight, BufferedImage.TYPE_INT_ARGB);
    Graphics2D g2 = bufferedImg.createGraphics();
    g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC);
    g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
    g2.drawImage(srcImg, 0, 0, newWidth, newHeight, null);
    g2.dispose();
    return bufferedImg;
}
    public EmployeeResolve(String user) {
        initComponents();
        this.user=user;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        comtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);

        comtable.setBackground(new java.awt.Color(255,255,255,80));
        comtable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        comtable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Complaint ID", "Cust ID", "Type", "Level", "Image"
            }
        ));
        comtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comtableMouseClicked(evt);
            }
        });
        comtable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                comtableComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(comtable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(786, 131, 657, 570);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Complaint ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 230, 120, 40);

        jTextField1.setBackground(new java.awt.Color(255,255,255,80));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(300, 230, 327, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Solution");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 370, 70, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Status");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 500, 60, 30);

        jTextArea1.setBackground(new java.awt.Color(255,255,255,80));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(300, 340, 330, 87);

        jComboBox1.setBackground(new java.awt.Color(255,255,255,80));
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "On Going", "Solved" }));
        jComboBox1.setBorder(null);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(300, 500, 330, 30);

        jButton1.setBackground(new java.awt.Color(255,255,255,80));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 680, 70, 30);

        jButton2.setBackground(new java.awt.Color(255,255,255,80));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(550, 680, 70, 30);

        jPanel1.setBackground(new java.awt.Color(0,0,0,90));
        jPanel1.setLayout(null);

        imageLabel.setBackground(new java.awt.Color(255, 255, 255));
        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.add(imageLabel);
        imageLabel.setBounds(650, 220, 70, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1550, 810);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\sem IV\\project\\login bg.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -10, 1540, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comtableMouseClicked
        int index=comtable.getSelectedRow();
        TableModel model=comtable.getModel();
        String id=model.getValueAt(index,0).toString();
        jTextField1.setText(id);
         try {
        Connection con = ConnectionProvider.getCon();
        PreparedStatement pst = con.prepareStatement("SELECT image FROM ecomplaint WHERE ComplaintID = ?");
        pst.setString(1, id);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            byte[] imgData = rs.getBytes("image");

            if (imgData != null) {
                ImageIcon icon = new ImageIcon(imgData);
                Image img = icon.getImage().getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);
                imageLabel.setIcon(new ImageIcon(img));
            } else {
                imageLabel.setIcon(null); 
                JOptionPane.showMessageDialog(null, "No image available for this record.");
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error loading image: " + e.getMessage());
    }

    }//GEN-LAST:event_comtableMouseClicked

    private void comtableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_comtableComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_comtableComponentShown

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id=jTextField1.getText();
        String d =jTextArea1.getText();
        String s=(String)jComboBox1.getSelectedItem();
        Connection con = null;
        try {
        con = ConnectionProvider.getCon();
        Statement st = con.createStatement();
        if (s.equals("Solved")) {
           st.executeUpdate("INSERT INTO solved_ecomplaint (ComplaintID, CustID, Type, Description, Incident, ComDate, Level, image, Status, assign, solution) " +
                 "SELECT ComplaintID, CustID, Type, Description, Incident, ComDate, Level, image, 'Solved', assign, '" + d + "' " +
                 "FROM ecomplaint WHERE ComplaintID = '" + id + "'");

            st.executeUpdate("DELETE FROM ecomplaint WHERE ComplaintID = '" + id + "'");
            
            JOptionPane.showMessageDialog(null, "Complaint marked as solved and moved to solved_ecomplaint.");
        } else {
            st.executeUpdate("UPDATE ecomplaint SET solution='" + d + "', status='" + s + "' WHERE ComplaintID='" + id + "'");
            JOptionPane.showMessageDialog(null, "Complaint updated successfully.");
        }
       }
        catch(SQLException e)
        {
             if (con != null) try {
                 con.rollback();
             } catch (SQLException ex) {
                 Logger.getLogger(EmployeeResolve.class.getName()).log(Level.SEVERE, null, ex);
             }
            JOptionPane.showMessageDialog(null,"Error: " + e.getMessage());
            setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
          try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select ecomplaint.ComplaintID,ecomplaint.custID,ecomplaint.Type,ecomplaint.Level,ecomplaint.image from ecomplaint where assign='"+user+"'");
            comtable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Connection Error"+e.getMessage());
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeResolve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeResolve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeResolve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeResolve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               EmployeeResolve er = new EmployeeResolve();
               er.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
               er.setVisible(true);
               er.toFront();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable comtable;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
