import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project.ConnectionProvider;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
public class LoginPage extends javax.swing.JFrame {
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        user1 = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\sem IV\\project\\shal logo.png")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 260, 270, 170);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SEA HAWK LINES PRIVATE LIMITED");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 400, 660, 140);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("\"Sailing Beyond Boundaries, Delivering with Excellence\"");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 500, 470, 21);

        jPanel1.setBackground(new java.awt.Color(0,0,0,80));
        jPanel1.setMaximumSize(new java.awt.Dimension(769, 900));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 290, 96, 33);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 400, 96, 33);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Role");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 510, 96, 33);

        jComboBox1.setBackground(new java.awt.Color(255,255,255,80));
        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Customer", "Employee" }));
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(210, 560, 330, 30);

        jButton2.setBackground(new java.awt.Color(255,255,255,80));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Login ");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(310, 650, 150, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sign in");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(310, 190, 150, 90);

        user1.setBackground(new java.awt.Color(255,255,255,80));
        user1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        user1.setForeground(new java.awt.Color(255, 255, 255));
        user1.setBorder(null);
        jPanel1.add(user1);
        user1.setBounds(210, 340, 330, 30);

        password.setBackground(new java.awt.Color(255,255,255));
        password.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        password.setBorder(null);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password);
        password.setBounds(210, 450, 330, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(790, 0, 750, 810);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Downloads\\sem IV\\project\\login bg.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -10, 1580, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            String pass = null;
            String id=null;
            String role=(String)jComboBox1.getSelectedItem();
            String us=user1.getText();
            Connection con = ConnectionProvider.getCon();
            Statement st=con.createStatement();
            switch (role) {
                case "Admin" ->                     
                {    
                        ResultSet rs=st.executeQuery("select * from AdminLogin  where username='"+us+"'");
                        if(rs.next())
                        {
                            pass=rs.getString(3);
                            id=rs.getString(1);
                           
                        }
                        if((new String(password.getPassword()).equals(pass)))
                        {
                            setVisible(false);
                            Home home = new Home(us);
                            home.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
                            home.setVisible(true);
                            home.toFront();

                            
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"Incorrect Username or Password or Role");
                        }
                }
                case "Customer" ->                     {
                        ResultSet rs=st.executeQuery("select CustomerID,Password from customer  where Username='"+us+"'");
                        if(rs.next())
                        {
                            pass=rs.getString(2);
                            id=rs.getString(1);
                        }       
                        if(new String(password.getPassword()).equals(pass))
                        {
                            setVisible(false);
                            setVisible(false);
                            Home2 home2 = new Home2(id);
                            home2.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
                            home2.setVisible(true);
                            home2.toFront();
                            
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"Incorrect Username or Password or Role");
                        }
                }
                case "Employee" ->                     {
                        ResultSet rs=st.executeQuery("select employeeID,Password from Employee where username='"+us+"'");
                        if(rs.next())
                        {
                            id=rs.getString(1);
                            pass=rs.getString(2);
                           
                        }
                        if(new String(password.getPassword()).equals(pass))
                        {
                            setVisible(false);
                            Home1 home1 = new Home1(us);
                            home1.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
                            home1.setVisible(true);
                            home1.toFront();
                            
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"Incorrect Username or Password or Role");
                        }
                }
                default -> JOptionPane.showMessageDialog(null,"Incorrect Username or Password or Role");
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginPage lp = new LoginPage();
                lp.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
                lp.setVisible(true);
                lp.toFront();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField user1;
    // End of variables declaration//GEN-END:variables
}
